conky.config = {
    alignment = 'top_left',
    background = black,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'green',
    double_buffer = true,
    draw_borders = true,
    draw_graph_borders = true,
    draw_outline = true,
    draw_shades = true,
    font = 'Lucida Console:size=10',
    gap_x = 500,
    gap_y = 250,
    minimum_width = 400,
    maximum_width = 400,
    minimum_height = 300,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_x = true,
    own_window = true,
    own_window_type = 'dock',
    own_window_transparent = false,
    own_window_colour = '000000',
    own_window_argb_visual = true,
    own_window_argb_value = 255,
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',
    update_interval = 3,
    use_xft = true,

}

conky.text = [[
${color red}${font  Abnes:bold:size= 12}${alignr}${time %A, %d %B}
${color violet}[*] INTERNET STATUS: ${color violet}${exec bash -c "ping -c 1 -W 2 8.8.8.8 >/dev/null 2>&1 && echo UP || echo DOWN"}
$hr
${color cyan}[*] serveo.net:22 >> ${exec nc -z -w 5 serveo.net 22 && echo "open" || echo "closed"}
${color grey}[*] System :$color $sysname $nodename $kernel
$hr
${color cyan}[*] GATEWAY PAGEKITE :
${font Orbitron:size=15}${execi 60 curl -s http://tsilavina.mywebcommunity.org/urls.php && echo "UP" || echo "NO INTERNET"}  ${font}
$hr
${color grey}${font Orbitron:size=10}[+] COMMANDER :${color green}Cybergorad${font}
${color grey}[*] Uptime :$color $uptime
${color grey}[*] RAM :$color $mem/$memmax - $memperc% ${membar 4}
${color grey}[*] CPU :$color $cpu% ${cpubar 4}
$hr
${color grey}[*] IP ADDRESS :
-> enp4s0 ${color green}${if_up enp4s0}${addr enp4s0}${else}${color red}Disconnected${endif}
-> wlo1: ${color green}${if_up wlo1}${addr wlo1}${else}${color red}Disctonnected${endif}
${color grey}-> wlx1c1ee3a8ae8a : ${color green}${if_up wlx1c1ee3a8ae8a}${addr wlx1c1ee3a8ae8a}${else}${color red}Disconnected${endif}
]]
