conky.config = {
    alignment = 'top_left',
    background = black,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'green',
    double_buffer = true,
    draw_borders = true,
    draw_graph_borders = true,
    draw_outline = true,
    draw_shades = true,
    font = 'Lucida Console:size=10',
    gap_x = 500,
    gap_y = 250,
    minimum_width = 400,
    maximum_width = 400,
    minimum_height = 300,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_x = true,
    own_window = true,
    own_window_type = 'dock',
    own_window_transparent = false,
    own_window_colour = '000000',
    own_window_argb_visual = true,
    own_window_argb_value = 255,
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',
    update_interval = 3,
    use_xft = true,

}



conky.text = [[
${color cyan}--- LIVE LOGS: MULTI-GORAD ---
${color green}${font Abnes:bold:size=7}${execpi 1 tail -n 15 /home/cybergorad/Desktop/log/multi-gorad.log | \
sed -e 's/Disconnected/${color red}Disconnected/g'
]]
