conky.config = {
    alignment = 'top_left',
    background = black,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'green',
    double_buffer = true,
    draw_borders = true,
    draw_graph_borders = true,
    draw_outline = true,
    draw_shades = true,
    font = 'Lucida Console:size=10',
    gap_x = 500,
    gap_y = 250,
    minimum_width = 200,
    maximum_width = 200,
    minimum_height = 50,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_x = true,
    own_window = true,
    own_window_type = 'dock',
    own_window_transparent = false,
    own_window_colour = '000000',
    own_window_argb_visual = true,
    own_window_argb_value = 255,
    own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',
    update_interval = 3,
    use_xft = true,
}
conky.text = [[
${color grey}SYSTEM STATUS${hr 2}
${color white}Service Tunel: ${alignr}${if_match "${exec systemctl is-active tunel}" == "active"}${color green}EN LIGNE${else}${color red}HORS LIGNE${endif}
${color white}${alignr}${exec systemctl show tunel --property=ActiveEnterTimestamp | cut -d= -f2}
${color grey}${hr 2}
${color white}IP Publique: ${alignr}${execi 3600 curl -s https://ifconfig.me}
]]
